# Generated by Django 3.0.5 on 2020-04-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('unit_cost', models.IntegerField()),
                ('rrp', models.IntegerField()),
                ('average_fee', models.IntegerField()),
                ('shipping_fee', models.IntegerField()),
            ],
        ),
    ]
