# Generated by Django 3.0.5 on 2020-04-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clutter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=64)),
                ('contact', models.CharField(max_length=64)),
                ('email', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='agent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='clutter.Supplier'),
        ),
    ]
