# Generated by Django 3.0.5 on 2020-04-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clutter', '0002_auto_20200412_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_fee',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='rrp',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
