# Generated by Django 3.0.5 on 2020-04-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clutter', '0003_auto_20200412_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=64)),
                ('contact', models.CharField(max_length=64)),
                ('email', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
