# Generated by Django 3.0.5 on 2020-04-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clutter', '0005_auto_20200419_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True),
        ),
    ]
