# Generated by Django 3.0.5 on 2020-04-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clutter', '0006_product_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_link',
            field=models.CharField(default=None, max_length=164, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ebay_link',
            field=models.CharField(default=None, max_length=164, null=True),
        ),
    ]
